name: Build docs-verifier
on: [pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
      - name: Try get cached dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Validate dependencies
        run: dotnet restore actions/docs-verifier --locked-mode --packages ${{ github.workspace }}/.nuget/packages
      - name: Build
        run: dotnet msbuild actions/docs-verifier -noLogo -m -p:Configuration=${{ matrix.configuration }} -warnaserror -bl:artifacts/log/build.binlog
      - name: Test
        run: dotnet test actions/docs-verifier
      - name: Upload Results
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ matrix.os }}_${{ matrix.configuration }}
          path: |
            ./artifacts/bin/**/*
            ./artifacts/log/**/*
          if-no-files-found: error
